# Generated by Django 4.0.4 on 2022-05-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentRegister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='position',
            new_name='Language',
        ),
    ]
