# Generated by Django 4.0.4 on 2022-05-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentRegister', '0002_rename_position_student_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Language',
            new_name='position',
        ),
    ]
