# Generated by Django 4.0.4 on 2022-05-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRegister', '0003_rename_language_student_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
