# Generated by Django 4.0.4 on 2022-05-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRegister', '0004_alter_student_fullname_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(error_messages={'unique': 'this name is already registered'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(error_messages={'unique': 'this id is already registered'}, max_length=10, unique=True),
        ),
    ]
