# Generated by Django 4.0.4 on 2022-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRegister', '0005_alter_student_fullname_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
